### ISSUE TITLE
[start_ursim] Sharing of urcap and program storage in series can lead to errors

### ISSUE THREAD

**Issue by RobertWilbrandt** [UniversalRobots/Universal_Robots_Client_Library#190] opened 2023-11-30 10:24 UTC
`start_ursim.sh` defaults to using `${PERSISTENT_BASE}/${ROBOT_SERIES}` as base for urcap and program storage. This means that the same storage is shared between different robots of a series which can lead to errors:
1. `rm -rf ~/.ursim/e-series`
2. `ros2 run ur_client_library start_ursim.sh -m ur5e`
    This will create the relevant files and a safety configuration with 191 deg/s for each joint.
3. `ros2 run ur_client_library start_ursim.sh -m ur10e`
    This shares the safety configuration, leading to safety errors as soon as you go to the installation tab, as the joint limits for the first two joints are only allowed to go up to 131 deg/s for this arm.

This should be fixed to allow for easier switching between simulated robots.

**Comment by VinDp** [comment] 2024-05-29 11:48
The issue is fixed by [#201](https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/201#pullrequestreview-2085170997).

**Closed by VinDp** 2024-05-29 11:48 UTC
Labels: bug
